### ISSUE TITLE
Export between two dates

### ISSUE THREAD

**Issue by ortegafernando** [InfinityWorldHI/Biometric-attendance-system-V1.0#1]
Hi, great job !!!

Is it a possibility to export between two dates? 

Thanks a lot.

**Comment by InfinityWorldHI** [comment]
Hello. thanks.
What do you mean?

**Comment by ortegafernando** [comment]
Hi, I mean that your php code lets you to export log from ONE date, it will be great that you update your code so we could choose start date and end date to export to excel. (I'm not expert in php language)

**Comment by InfinityWorldHI** [comment]
Sound good.
Ok, I will consider that.
